# Build and deploy Node.js app to Azure Web App - GitHubActionsQuiz

name: Build and deploy Node.js app to Azure Web App - GitHubActionsQuiz

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Prepare wwwroot folder
        run: |
          mkdir -p wwwroot
          cp -a dist/. wwwroot/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: wwwroot

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73CEDB97F5924806BF5652F0007FDBFE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B13BB0205F6C4DE69DAA7CFED4896F2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_711FA46DDBF9445D845B90CE76DFFE7E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GitHubActionsQuiz'
          slot-name: 'Production'
          package: .
